In [2]:
import csv
from pathlib import Path
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
DATA_DIR = Path("./src/mnistdigits/")

True

In [6]:
TRAIN_FILE_PATH = DATA_DIR / "mnist_train.csv"
TEST_FILE_PATH = DATA_DIR / "mnist_test.csv"

In [21]:
training_data = pd.read_csv(TRAIN_FILE_PATH)
testing_data = pd.read_csv(TEST_FILE_PATH)
training_data.head()

,5,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.608,0.609,0.610,0.611,0.612,0.613,0.614,0.615,0.616,0.617
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
train_y = training_data.iloc[:,0]
train_x = training_data.drop(training_data.columns[[0]], axis=1)
test_y = testing_data.iloc[:,0]
test_x = testing_data.drop(testing_data.columns[[0]], axis=1)

In [26]:
test_x

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(784,)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax),
])
model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()],
)

In [52]:
history = model.fit(
    train_x,
    train_y,
    epochs=10,
    validation_split=0.15,
)

Epoch 1/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6424 - sparse_categorical_accuracy: 0.8130 - val_loss: 0.4769 - val_sparse_categorical_accuracy: 0.8979
Epoch 2/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.4374 - sparse_categorical_accuracy: 0.9005 - val_loss: 0.3490 - val_sparse_categorical_accuracy: 0.9178
Epoch 3/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3085 - sparse_categorical_accuracy: 0.9221 - val_loss: 0.3156 - val_sparse_categorical_accuracy: 0.9186
Epoch 4/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.2726 - sparse_categorical_accuracy: 0.9307 - val_loss: 0.2702 - val_sparse_categorical_accuracy: 0.9413
Epoch 5/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 0.2332 - sparse_categorical_accuracy: 0.9417 - val_loss: 0.2625 - val_sparse_categorical_accuracy: 0.9428
Epoch 6/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2299 - sparse_categorical_accuracy: 0.9435 - val_loss: 0.2730 - val_sparse_categorical_accuracy: 0.9382
Epoch 7/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2133 - sparse_categorical_accuracy: 0.9465 - val_loss: 0.2201 - val_sparse_categorical_accuracy: 0.9489
Epoch 8/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.1896 - sparse_categorical_accuracy: 0.9524 - val_loss: 0.2558 - val_sparse_categorical_accuracy: 0.9457
Epoch 9/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.1918 - sparse_categorical_accuracy: 0.9527 - val_loss: 0.2588 - val_sparse_categorical_accuracy: 0.9512
Epoch 10/10
1594/1594 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.1661 - sparse_categorical_accuracy: 0.9589 - val_loss: 0.2495 - val_sparse_categorical_accuracy: 0.9482

In [66]:
test_digits = test_x.iloc[0:100]
predictions = model.predict(test_digits)
pred1 = predictions[75]
digit_pred = np.argmax(pred1)
print(digit_pred)
print(test_y.iloc[75])

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
3
3